apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
      env: production
  template:
    metadata:
      name: nginx
      labels:
        app: myapp
        env: production
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
